kind: Secret
apiVersion: v1
metadata:
  name: sidecar-injector
  namespace: default
  labels:
    app: sidecar-injector
type: kubernetes.io/tls
data:
  tls.crt: ${TLS_CERT}
  tls.key: ${TLS_KEY}

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: sidecar-injector
  namespace: default
  labels:
    app: sidecar-injector

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sidecar-injector
  namespace: default
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sidecar-injector
  namespace: default
subjects:
- kind: ServiceAccount
  name: sidecar-injector
  apiGroup: ""
roleRef:
  kind: Role
  name: sidecar-injector
  apiGroup: rbac.authorization.k8s.io

---
kind: Service
apiVersion: v1
metadata:
  name: sidecar-injector
  namespace: default
  labels:
    app: sidecar-injector
spec:
  selector:
    app: sidecar-injector
  ports:
  - port: 443
    targetPort: https

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: sidecar-injector
  namespace: default
  labels:
    app: sidecar-injector
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: sidecar-injector
  template:
    metadata:
      labels:
        app: sidecar-injector
    spec:
      serviceAccount: sidecar-injector
      containers:
      - name: server
        image: isim/sidecar-injector:0.0.1
        imagePullPolicy: Always
        args:
        - -debug
        - "${DEBUG_ENABLED}"
        ports:
        - name: https
          containerPort: 443
        volumeMounts:
        - name: tls
          mountPath: /etc/secret
          readOnly: true
      volumes:
      - name: tls
        secret:
          secretName: sidecar-injector

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: sidecar-injector-configuration
  namespace: default
  labels:
    app: sidecar-injector
webhooks:
  - name: sidecar-injector.example.org
    clientConfig:
      service:
        name: sidecar-injector
        namespace: default
        path: "/"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
